# PiBook — DHCP local do hotspot

# DNS do portal cativo PiBook
port=53
no-resolv
domain-needed
bogus-priv
address=/#/10.42.0.1
local=/pibook/
address=/pibook/10.42.0.1
dhcp-option=option:dns-server,10.42.0.1
interface=wlan0
bind-interfaces
dhcp-authoritative
dhcp-range=10.42.0.20,10.42.0.200,255.255.255.0,1h
dhcp-option=option:router,10.42.0.1
dhcp-option=option:mtu,1500
dhcp-leasefile=/run/pibook-network/dnsmasq.leases
pid-file=/run/pibook-network/dnsmasq.pid
log-dhcp
